### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by wschoenell** [danjampro/DeepScan#1]
Dear @danjampro,

Thanks for sharing your code!!! I tried to contact you directly by e-mail, but it seems that your University's server is not working :(

I saw your pre-print in the arxiv few days ago and got very interested on using it, as I have a bunch of deep data that I'd like to find LSB stuff. I tried to run what I think that is the basic example and I saw that the wsize here https://github.com/danjampro/DeepScan/blob/fc2c1a6c0bf8bc2b02953adf3e2cb3cd0df3aa88/vignettes/ngvs_small.py#L31 does not exist on the function definition here https://github.com/danjampro/DeepScan/blob/fc2c1a6c0bf8bc2b02953adf3e2cb3cd0df3aa88/deepscan/skymap.py#L478-L482.

It seems that something is missing or outdated...

So I decided to write you and ask for a running example so I can test your code and even contribute with you. Can you help me with that? :-)

All the best!!

**Comment by danjampro** [comment]
Hi William! Thanks for your interest. Certainly the vignettes are out of date, and I should update my email address to the correct version! I will hopefully get some basic examples done over the next few days. Is there anything specific you might want?

Cheers,
Dan
